### ISSUE TITLE
Is it possible to have a mock method that can return itself?

### ISSUE THREAD

**Issue by seanybaggins** [asomers/mockall#106] opened 2020-03-10 18:39 UTC
I have a set of methods where the output of one serves as an input to the next. 

Here is where I end up calling the methods 
```rust

lazy_static! {
    // Opening the pipe with write permissions will block until the reader opens the file as well.
    pub static ref TO_UI: Mutex<File> = Mutex::new(OpenOptions::new()
        .append(true)
        .create_new(false)
        .open(PATH_TO_UI_PIPE)
        .unwrap() // Not sure how we want to handle an error here.
    );   
}
```
Here are my mocks definitions(all defined within the same file).
```rust

        mock! {
            pub File {}
            trait Write {
                fn write(&mut self, buf: &[u8]) -> io::Result<usize>;
                fn flush(&mut self) -> io::Result<()>;
            }
        }

        use MockFile as File;

        mock! {
            pub OpenOptions {
                fn open<P: AsRef<Path> + 'static>(&self, path: P) -> io::Result<File>;
                fn append(&mut self, append: bool) -> &mut OpenOptions;
                fn create_new(&mut self, create_new: bool) -> &mut OpenOptions;
                fn read(&mut self, read: bool) -> &mut OpenOptions;
                fn new() -> OpenOptions;
            }
        }

        use MockOpenOptions as OpenOptions;
   
```

In my test I have
```rust
    // Setting up mocks for UI
    let mut mock_open_options = MockOpenOptions::default();
    mock_open_options.expect_append()
        .return_var(MockOpenOptions::default());
    mock_open_options.expect_create_new()
        .return_var(MockOpenOptions::default());
    mock_open_options.expect_open()
        .returning(|_: &str| Ok(MockFile::new()));
```

The problem is after I return `MockOpenOptions::default()`  for the `expect_append()` the rest of my `return_var` statements for `mock_open_options` don't do anything because the instance of `mock_open_options` did not get returned. Instead a new instance of `MockOpenOptions` was returned

Is there a way to modify `MockOpenOptions::default()` return value or to have a `return_var`, return `self`?

**Comment by asomers** [comment] 2020-03-11 04:28
The problem is that all of your expectations are set for one specific mock object, not for any instance of the class.  And nothing returns that one instance to the caller.  You could do it instead like this:
```rust
MockOpenOptions::expect_new()
    .returning(|| {
        let first = MockOpenOptions::default();
        first.expect_append()
            .returning(|| {
                ...
            })
        first
    })
```
You'll need to go a fewer layers deeper, of course.  But in this specific instance, there's a much easier way.  Just do
```rust
#[cfg(not(test))]
lazy_static! {
    // Opening the pipe with write permissions will block until the reader opens the file as well.
    pub static ref TO_UI: Mutex<File> = Mutex::new(OpenOptions::new()
        ...
    );
)
#[cfg(test)]
lazy_static! {
    pub static ref TO_UI: Mutex<File> = Mutex::new(MockFile::new())
}
```

**Comment by seanybaggins** [comment] 2020-03-11 21:10
Wow! Thank you for that feedback. That is such a better/more simple way of mocking this stuff out. My problem is solved. 

Should I close this issue or leave it open for an enhancement in the future to have a mock be able to return mutable and static references to itself?

**Comment by asomers** [comment] 2020-03-11 21:27
No, let's close it.  Reopen if you find a situation where neither of my two above suggestions is applicable.

**Closed** 2020-03-11 21:28 UTC
Labels: question
