### ISSUE TITLE
Advice for specific case 

### ISSUE THREAD

**Issue by brpatel12** [asomers/mockall#122] opened 2020-04-27 23:19 UTC
```
pub struct StructA {}
impl StructA {
     fn one(num: i32) -> i32 { num }
}

pub StructB {
    holds: StructA
}
impl StructB {
    fn three(&self, num2: i32) -> i32 {
       2 * self.holds.one(num2)
    }
}

mock! {
    pub StructA {
        fn one() -> i32;
    }
}

// I want to test that fn three(&self, i32) -> i32 does
// 2 * blackbox rather than 2 * StructA::one()

// the following is pseudo code for what I'm looking to do.
#[cfg(test)]
mod tests {
    let mock = MockStructA::new();
    // when I tried this I got an error because MockStructA != StructA
    let server = StructB { holds: mock }; 
    let num = 2;
    mock.expect_fn_one_call().args(num).returns(2);
    assert_eq!(server.three(num), 4);
}
```

**Comment by asomers** [comment] 2020-04-28 03:58
Firstly, the mock version of `StructA::one` doesn't match the signature of the real version.  But you're real question is about how to store a `MockStructA` within `StructB` rather than a real `StructA`.  The key is to use namespace, as described at https://docs.rs/mockall/0.7.0/mockall/#mocking-structs .  You need to put `StructA` inside of a module.  Then you can selectively use either `some_module::StructA` or `some_module::MockStructA as StructA`.

**Comment by asomers** [comment] 2020-05-19 16:36
Closing with ETIMEOUT.  Feel free to reopen if you still have questions.

**Closed by asomers** 2020-05-19 16:36 UTC
Labels: question

**Comment by brpatel12** [comment] 2020-06-10 01:52
I may be doing the "selectively use either some_module::StructA or some_module::MockStructA as StructA" incorrectly but I'm still running into

```expected struct `store::module::Store`, found struct `store::module::MockStore```

here's what I have

```
mod module {
    pub struct Store {}
    #[automock]
    impl Store {
       <some methods>
    }
}
```
pub struct DependsOnStore {
    pub store: module::Store,
}

[#cfg(test)[
mod test {
    use store::module::MockStore as Store;
    use mockall::predicate::*;
    [#test]
    fn test_mock() {
        DependsOnStore{ store: Store::new() };
    }
}
```

**Comment by asomers** [comment] 2020-06-10 02:34
The problem is that you're using the real Store in one place and the mock Store in another.  You need to use them consistently, like this:
```rust
#[cfg(not(test))]
use store::module::Store;
#[cfg(test)]
use store::module::MockStore as Store;

pub struct DependsOnStore {
    pub store: Store,
}

[#cfg(test)]
mod test {
    use mockall::predicate::*;
    [#test]
    fn test_mock() {
        DependsOnStore{ store: Store::new() };
    }
}
```

**Comment by brpatel12** [comment] 2020-06-10 05:27
I guess let me ask this more generally. 

File 1: Some module which wraps a database and provides some API for it. 

File 2: Struct `DependsOnStore` which has a handle to this `Store`s public API (I thus wouldn't want it holding a mock object) - when writing unit tests in File 2 for `DependsOnStore` I want to mock the functionality I'd see from `DependsOnStore`s `Store` struct. Does this use case make sense? Let me know if I should further clarify.

**Comment by brpatel12** [comment] 2020-06-11 04:05
Update: got everything working! Thanks for the help.

Also for what it's worth, I didn't need to wrap Store in a module for the mock to work (it worked both wrapped in a module and raw).

**Comment by timstepro** [comment] 2023-04-18 00:19
Hey @asomers, I'm running into the same issue. Your solution worked like a charm. 

How could we get around this with the `!mock` macro? Is that possible?

**Comment by asomers** [comment] 2023-04-18 00:28
I don't understand @timstepro .  What are you hoping that `mock!` will do?  The OP's problem was that he imported the real struct in one place and the mock one in another.

**Comment by timstepro** [comment] 2023-04-18 00:57
Sorry, just realized that `mock!` won't change anything. 

I'm following OP's pattern. I'm trying to use a mock and the original in the same file. Can I do this without the `#[cfg(test)]` and `#[cfg(not(test))]` annotations? I'm trying to keep this all isolated in the test module. Not sure if that's a good pattern or not.

**Comment by asomers** [comment] 2023-04-18 01:51
It's fine to use them both in the same file.  But it will be much easier if you put them into a submodule within that file.
