### ISSUE TITLE
Need help for an easy test case

### ISSUE THREAD

**Issue by hommeabeil** [asomers/mockall#286] opened 2021-06-10 11:54 UTC
I am really struggling with the unit testing and mocking in Rust. I simply try to inject a mock to be able to test some IO operation, in this case via a socket (UDP). I came up with the following solution (not perfect, but simple enough) and I tried your lib for the test. However, the `'static` restriction on generic type seems to prevent me from mocking the `MySocket` trait. Is there any way around this or I am again the wall ? Maybe I re-organize my struct or something else ?

Thanks, and your mock lib is truly the more advance out there.

```rust
#[automock]
pub trait MySocket {
    fn connect<T : AsRef<Path>(path: T) -> std::io::Result<()>;
}

struct Client<T: MySocket> {
    socket: T
}

impl<T: MySocket> Client<T> {

    fn new(socket: T) -> Self { Client{socket} };
}

```

**Comment by asomers** [comment] 2021-06-10 16:03
By far the easiest course of action would be to add a `'static` bound to your trait, like this:
```rust
#[automock]
pub trait MySocket {
    fn connect<T : AsRef<Path> + 'static>(path: T) -> std::io::Result<()>;
}
```
Would that work for you?

**Comment by hommeabeil** [comment] 2021-06-10 17:13
For this specific case yes it would, but I am in the course of learning Rust so I  try to find the proper way to do TDD and mocking is a huge part of it. Would it have an other solution with the current library implementation or this is really the current state of the art in doing mock in Rust ?

I understand the `Any` trait limitation and that we will not see this limitation removed from the compiler. Would it be possible to store a map per function with a concrete type so we can lift the `'static` limitation. Again working with a trait object (as you proposed in #217) will not work in this case since we have a generic method. Might be able to give a hand on this if you need.

**Comment by asomers** [comment] 2021-06-10 20:09
> I understand the `Any` trait limitation and that we will not see this limitation removed from the compiler. Would it be possible to store a map per function with a concrete type so we can lift the `'static` limitation. Again working with a trait object (as you proposed in #217) will not work in this case since we have a generic method. Might be able to give a hand on this if you need.

I've been thinking about that all morning.  But I can't see how it would work.  The problem is that Rust doesn't have any way to do something like a `match` over types.  Nothing like this, for example:
```rust
match<T>() {
    u32 => ...,
    impl Debug => ...,
    _ => ...
}
```
For concrete types, this would work if you used the `TypeID`.  But that, as you've discovered, requires `Any`.  The closest thing is specialization.  I think I could make that work.  But it wouldn't accomplish much, because Mockall still wouldn't be able to do anything with the non-`'static` types.  Those would fail at runtime instead of compile time.  So it wouldn't be much better than requiring you to add `+ 'static` to your function signatures.

**Comment by hommeabeil** [comment] 2021-06-12 10:35
Just out of curiosity, why do you need the `Any` type ? Is it for the predicate struct ? I am slowly looking at the source code to find my way around, but I can't find where the `Any` type is used.

**Comment by asomers** [comment] 2021-06-12 13:09
`Any` is required for downcasting, and is used via the `downcast` crate.  For generic functions, Mockall stores both Predicates and returner functions (as set by `withf`) as `Box<Any>` and downcasts them when needed.

**Comment by asomers** [comment] 2021-06-20 14:02
I'm going to close this, because I think I've answered all of your questions.  You can reopen it if I haven't.

**Closed by asomers** 2021-06-20 14:02 UTC
Labels: question

**Comment by hommeabeil** [comment] 2021-06-22 00:23
Thank you for your response. I will need to play a little bit more to fully understand all.
