### ISSUE TITLE
Compatibility with rust-analyzer

### ISSUE THREAD

**Issue by aaomidi** [asomers/mockall#251] opened 2021-02-08 20:34 UTC
Is there anything special that needs to be done to make this work with rust-analyzer? I saw this issue: https://github.com/rust-analyzer/rust-analyzer/issues/7034

And these are my current rust-analyzer settings:

```
    "rust-analyzer.cargo.allFeatures": true,
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
    "rust-analyzer.procMacro.enable": true,
    "rust-analyzer.updates.channel": "nightly",
    "rust-analyzer.trace.extension": true,
    "rust-analyzer.diagnostics.enable": true,
    "rust-analyzer.diagnostics.enableExperimental": true,
```

Unfortunately rust analyzer thinks all of my mocked structs are "Unknown"

**Comment by asomers** [comment] 2021-02-08 20:37
Good question.  I don't know the answer, because I don't use rust-analyzer.  But if you do find a solution, please post it here.

**Comment by asomers** [comment] 2021-02-13 05:52
It looks like the original issue has been fixed by a change in rust-analyzer.  Are you using the latest version?  If you are, try opening a new issue with rust-analyzer first.

**Comment by DanielJoyce** [comment] 2021-04-13 15:48
Still looks like mock_all::double is borked because Rust Analyzer doesn't properly support attribute proc macros?

**Comment by asomers** [comment] 2021-04-13 15:55
@DanielJoyce that sounds like an issue with rust-analyzer.  Have you sought help there?

**Comment by DanielJoyce** [comment] 2021-04-21 18:44
rustc version 1.51, ubuntu

Well now I am seeing weird behavior with normal cargo test, where it doesn't seem to be seeing the mocked variant.

I am doing something like this

``` rust
mod some_client;
pub mod client {
    #[mockall_double::double]
    pub use super::client::Client;
}
```

When expanded in test mode I see
``` rust
mod some_client;
pub mod client {
    #[cfg(test)]
    pub use super::client::MockClient as Client;
}
```

The `#[cfg(test)]` seems spurious since `double` only emits the MockClient mapping anyways, and remove the Client export.

The problem is other code...

Client has a new() method that can fail, returning result

```
use crate::some_client::Client;

        match Client::new(
            some_value1,
            some_other_value2
        ) {
            Ok(result) => Outcome::Success(result),
            Err(error) => Outcome::Failure((Status::InternalServerError, error)),
        }

```

i get the following error with `cargo test`

```
  --> src/guard/client_guard.rs:35:44
   |
35 |             Ok(result) => Outcome::Success(result),
   |                                            ^^^^^^ expected struct `MockClient`, found struct client::Client`
```

This should not be possible, and I've been trying to figure out what is happening. I only export Client from the module, and double takes care of mapping it to Client or MockClient, yet the rust compiler gets confused.

**Comment by DanielJoyce** [comment] 2021-04-21 18:49
I don't want to sprinkle `double` everywhere, so I was hoping using it in a module re-export would work but maybe rustc 'sees' everything and gets confused, even though I use the module import?

**Comment by DanielJoyce** [comment] 2021-04-21 18:58
Oh, I suspect the "Result" being returned is not rewritten in the mock, This may apply to other wrapped types such as Option as well.

**Comment by DanielJoyce** [comment] 2021-04-21 19:00
PEBKAC

Changing return type of new() to Result<Self, SomeError> instead of Result<Client, SomeError> fixes it.

😛

**Comment by DanielJoyce** [comment] 2021-04-22 20:02
Bumped into this https://github.com/rust-analyzer/rust-analyzer/issues/8626 on rust-analyzer, which is related to this

https://github.com/rust-analyzer/rust-analyzer/issues/7459

changing do_double to this:
```rust
fn do_double(_attrs: TokenStream, input: TokenStream) -> TokenStream {
    let mut use_stmt: ItemUse = match parse2(input.clone()) {
        Ok(u) => u,
        Err(e) => return e.to_compile_error()
    };
    mock_itemuse(&mut use_stmt);
    if cfg!(test){
        quote!(
            #use_stmt
        )
    }else{
        quote!(
            #input
        )
    }
}
```
Fixes the issue, instead of a macro emitting two macros, it just emits the expected code. I can put in a PR, docs and tests would need to be updated.

**Comment by DanielJoyce** [comment] 2021-04-22 20:03
The tests fail as expected:

```
---- t::double::module stdout ----
thread 't::double::module' panicked at 'assertion failed: `(left == right)`
  left: `"use foo :: mock_bar as bar ;"`,
 right: `"# [cfg (not (test))] use foo :: bar ; # [cfg (test)] use foo :: mock_bar as bar ;"`', mockall_double/src/lib.rs:221:9

---- t::double::path stdout ----
thread 't::double::path' panicked at 'assertion failed: `(left == right)`
  left: `"use foo :: bar :: MockBaz as Baz ;"`,
 right: `"# [cfg (not (test))] use foo :: bar :: Baz ; # [cfg (test)] use foo :: bar :: MockBaz as Baz ;"`', mockall_double/src/lib.rs:221:9

---- t::double::rename stdout ----
thread 't::double::rename' panicked at 'assertion failed: `(left == right)`
  left: `"use MockFoo as Bar ;"`,
 right: `"# [cfg (not (test))] use Foo as Bar ; # [cfg (test)] use MockFoo as Bar ;"`', mockall_double/src/lib.rs:221:9

---- t::double::group stdout ----
thread 't::double::group' panicked at 'assertion failed: `(left == right)`
  left: `"use foo :: bar :: { MockBaz as Baz , MockBean as Bean } ;"`,
 right: `"# [cfg (not (test))] use foo :: bar :: { Baz , Bean } ; # [cfg (test)] use foo :: bar :: { MockBaz as Baz , MockBean as Bean } ;"`', mockall_double/src/lib.rs:221:9
```

**Comment by DanielJoyce** [comment] 2021-04-22 20:06
Hmm, but in actual use, it's not expanding the MockFoo as Foo line.

**Comment by DanielJoyce** [comment] 2021-04-22 20:08
Ahh, because the macro itself is not built in test mode, only when running tests. Back to the drawing board. 😝

**Comment by DanielJoyce** [comment] 2021-04-22 20:19
Yeah, it looks like it's an outstanding Rust Analyzer issue that may be fixed in the next few weeks.

**Comment by aymarino** [comment] 2021-06-02 23:57
The root rust-analyzer issue, for interested parties: rust-analyzer/rust-analyzer#6029.

**Comment by asomers** [comment] 2021-06-03 00:00
I'm going to close this issue, because I don't think there's anything to do on Mockall's side.

**Closed by asomers** 2021-06-03 00:00 UTC
