### ISSUE TITLE
Warning: mocked function never used

### ISSUE THREAD

**Issue by mlthlschr** [asomers/mockall#410] opened 2022-09-24 19:14 UTC
Hi,

since I updated my rust version on build I receive the warning that several of the mocked functions are never used, such as

```rust
...

warning: associated function `expect_count_items` is never used
  --> src/db/items.rs:32:14
   |
32 |     async fn count_items(&self) -> Result<i64, anyhow::Error>;
   |     

warning: associated function `expect` is never used
  --> src/db/items.rs:18:1
   |
18 | #[automock]
   | ^^^^^^^^^^^

...
```

Is there a way to fix/suppress that warning?

**Comment by asomers** [comment] 2022-09-24 19:46
What compiler version do you have, and how is your struct or trait defined?  The warnings probably wouldn't be emitted if the trait were `pub`.  Also, you probably want to use `#[cfg_attr(test, automock)]`, unless you actually want to ship the mocks in your finished library.

**Comment by mlthlschr** [comment] 2022-09-25 09:44
I use `rustc 1.64.0 (a55dd71d5 2022-09-19)`. 

The struct is defined like that:

```rust
#[async_trait]
#[automock]
pub(crate) trait Queries: Sync + Send {
    async fn count_items(&self) -> Result<i64, anyhow::Error>;
    // some more functions
    // the ones which are actually not used in tests are having a warning
}
```

Using `#[cfg_attr(test, automock)] instead of `#[automock]` actually fixed the problem compiler-wise. No more warning here. Only `rust_analyzer` is still showing the warning in the editor.

**Comment by asomers** [comment] 2022-09-25 14:31
So you're still seeing warnings for the expect_* methods?  I think it would make sense for Mockall to suppress those.

**Comment by mlthlschr** [comment] 2022-09-26 05:40
Yeah, exactly. After changing to `#[cfg_attr(test,automock)]` the warnings disappeared for `build`s and `check`s, but when running `test`s they are still there. That's not such a big problem anymore.

The warnings shown when building tests is every `expect_*` function I do not use in the tests.

**Comment by krojew** [comment] 2022-09-27 05:48
Can confirm - `expect_*` functions trigger the `dead_code` warning.

**Comment by asomers** [comment] 2022-09-27 19:12
You need to put `#[automock]` _before_ `#[async_trait]`.  I'm actually surprised that it compiled at all.  You probably would've run into bigger problems if you'd actually tried to set any expectations.
https://docs.rs/mockall/latest/mockall/#async-traits

**Comment by rharish101** [comment] 2022-11-26 23:31
How about an attr for methods that makes `automock` skip generating mocked versions? It should look like this:
```rust
#[automock]
trait MyTrait {
    fn foo(&self) -> u32;
    #[nomock]
    fn bar(&self, x: u32, y: u32) -> u32;
}
```

This way, `MockMyTrait` will only have `expect_foo` generated, not `expect_bar`. This should suppress warnings that `expect_bar` isn't used.

**Comment by asomers** [comment] 2022-11-27 00:06
@rharish101 the problem should be fixed by using automock and async_trait in the correct order. Or are you still seeing this warning?

**Comment by rharish101** [comment] 2022-11-27 01:52
Yes, I tried both positions, and `automock` still raises the warnings.

**Comment by asomers** [comment] 2022-11-27 05:59
@rharish101 you aren't the OP, so I assume that your code is different.  Would you please post it, along with your unwanted warnings?

**Comment by rharish101** [comment] 2022-11-27 12:02
Here's a sample project with the following structure:
```
.
├── Cargo.lock
├── Cargo.toml
└── src
    ├── foo.rs
    └── main.rs

1 directory, 4 files
```

`Cargo.toml`:
```toml
[package]
name = "dummy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
mockall = "0.11.3"
```

`main.rs`:
```rust
mod foo;

fn main() {
    println!("Hello, world!");
}
```

`foo.rs`:
```rust
#[cfg(test)]
use mockall::automock;

#[cfg_attr(test, automock)]
pub trait MyTrait<T> {
    fn foo(&self, x: T);
}
```

When simplifying my code into this dummy example, I noticed that the warnings are only raised if all the following happen:
- `MyTrait` is defined in a separate file that is loaded in `main.rs`. Storing it directly in `main.rs` didn't raise warnings.
- The type parameter `T` is needed. Changing `MyTrait` to not use type params and substituting `T` with `u32` didn't raise warnings.

Note that `async-trait` isn't used anywhere, since I can reproduce the warnings reliably without it.

**Comment by asomers** [comment] 2022-11-27 14:15
@rharish101 I can reproduce this problem only using Rust 1.64.0 and 1.65.0,, but not 1.63.0, 1.66.0-beta.2 (0040709e3 2022-11-20), or 1.67.0-nightly (b7bc90fea 2022-11-21).  So I assume it's related to a compiler bug.  Also, your problem is most definitely not related to the OP's, so I'm going to close the issue.  Feel free to open a new one if you continue to have problems with compilers other than 1.64.0 and 1.65.0.

**Closed by asomers** 2022-11-27 14:15 UTC
Labels: question

**Comment by guiyomh** [comment] 2022-12-12 16:14
Me too, I reproduce the problem with rust 1.65.
