### ISSUE TITLE
is it possible to mock enums?

### ISSUE THREAD

**Issue by TomPridham** [asomers/mockall#354] opened 2022-01-31 18:15 UTC
we have an enum like
```
#[derive(Clone, Deserialize, Serialize, Debug, PartialEq)]
pub enum SystemCall{
  ApplicationInfo,
  ...
  OsVersion,
}

impl SystemCall {
  run(c: SystemCall) -> Result<String>;
}
```
using `automock` gives me this error: `expected enum system_call::SystemCall, found struct MockSystemCall`
trying to use `mock!` like this
```
mock! {
    #[derive(Clone, Deserialize, Serialize, Debug, PartialEq)]
    pub enum SystemCall{};
    impl SystemCall {
        fn run(command: SystemCall) -> Result<String>;
    }
}
```
gives me this error
```
error: expected identifier
  --> src/system_call.rs:26:9
   |
26 |     pub enum SystemCall{};
   |               ^^^^
```
searching through the repo, it doesn't seem like it's currently possible

**Comment by asomers** [comment] 2022-01-31 20:15
Yeah, it works for me.

> using automock gives me this error: expected enum system_call::SystemCall, found struct MockSystemCall

Did that error come from the `#[automock]` invocation?  I'm guess it actually came from the site where you called `SystemCall::run`. The problem is that you're passing a argument of type `Self`, but it isn't named `self`.  I don't think Mockall can do that right now.  To fix it, change the run signature to `fn run(self) -> Result<String>`.

And `mock!` works too, but you have some syntax errors.  Do it like this:
```rust
mock! {
    #[derive(Clone, Debug, PartialEq)]
    pub SystemCall {
        pub fn run(command: SystemCall) -> Result<String>;
    }
}
```

**Comment by TomPridham** [comment] 2022-01-31 23:48
i think you were right that some of the issue was because we were using basically a self param that wasn't name self. i changed that and it's closer to working. i am also using `mockall_double` to replace the instances of `SystemCall` with `MockSystemCall`. using your `mock!` example, replacing the arg with `self`, i get the following errors.
```
20 | #[derive(PartialEq, Clone, Deserialize, Serialize, Debug)]
   |          --------- in this derive macro expansion
...
23 |     SC(SystemCall),
   |        ^^^^^^^^^^
   |
note: an implementation of `PartialEq<_>` might be missing for `MockSystemCall`
  --> src/system_call.rs:24:1
   |
24 | mock! {
   | ^^^^^ must implement `PartialEq<_>`
   = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider annotating `MockSystemCall` with `#[derive(PartialEq)]`
   |
24 | #[derive(PartialEq)]
```
this error is why i think it was not working specifically for enums. i might just make the enum impl a standalone function and mock that since that seems less complicated and i have done that elsewhere in our code successfully
```
error[E0599]: no associated item named `OSVersion` found for struct `MockSystemCall` in the current scope
  --> src/command.rs:95:50
   |
95 |             execute: Execute::SC(MockSystemCall::OSVersion),
   |                                                  ^^^^^^^^^ associated item not found in `MockSystemCall`
   |
  ::: src/system_call.rs:24:1
   |
24 | mock! {
   | ----- associated item `OSVersion` not found for this
```

**Comment by asomers** [comment] 2022-02-01 00:09
- The problem with `PartialEq` is that not all traits can be derived for mock objects.  But you can still generate a mock eq method like this:
```rust
mock! {
    #[derive(Clone, Debug)]
    pub SystemCall {
        pub fn run(command: SystemCall) -> Result<String>;
    }
    impl PartialEq for SystemCall {
        fn eq(&self, other: &MockSystemCall) -> bool;
    }
}
```
- The need to specify `MockSystemCall` rather than `SystemCall` for the type of `other` is a bug, and I'll fix it.
- The problem with `MockSystemCall::OSVersion` not resolving is actually real.  That's because `mock!` doesn't know that it's working on an enum rather than a struct, and there's no syntax that allows you to define those enum values.  For this reason, `mock!` won't currently work for enums.  Supporting enums would be nice, but would obviously require some syntax changes.

**Comment by asomers** [comment] 2022-02-01 00:14
See #355 for the problem with PartialEq.

**Closed** 2022-05-15 15:34 UTC
Labels: question
