### ISSUE TITLE
Can't mock Option<&str> without an explicit lifetime name

### ISSUE THREAD

**Issue by olvyko** [asomers/mockall#82] opened 2019-11-21 14:05 UTC
Can't mock trait with Option<&str> without an explicit lifetime name:
```rust
#[cfg(test)]
mod tests {
    use mockall::*;

    #[automock]
    pub trait Mailer {
        fn send(&self, email: Option<&str>);
    }
}
```
Error:
```sh
error[E0637]: `&` without an explicit lifetime name cannot be used here
  --> modules\user\src\services\entry\usecase.rs:32:38
   |
32 |         fn send(&self, email: Option<&str>);
   |                                      ^ explicit lifetime name needed here

error[E0106]: missing lifetime specifier
  --> modules\user\src\services\entry\usecase.rs:32:38
   |
32 |         fn send(&self, email: Option<&str>);
   |                                      ^ expected lifetime parameter
```

**Comment by asomers** [comment] 2019-11-21 14:25
Duplicate of #61 .

**Closed by asomers** 2019-11-21 14:25 UTC
